[package]
name = "silverfish"
version = "0.1.0"
authors = ["Gregor Peach <gregorpeach@gmail.com>"]
edition = "2018"

[dependencies]
llvm-alt = { git = "https://github.com/gwsystems/llvm-rs.git"}
structopt = "0.2"
wasmparser = "0.29"

[profile.release]
debug = true
